apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-operator
  template:
    metadata:
      labels:
        name: kafka-operator
    spec:
      serviceAccountName: kafka-operator
      containers:
        - name: kafka-operator
          # Replace this with the built image name
          image: jianzhiunique/kafka-operator:v1.0.0
          command:
          - kafka-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kafka-operator"
